stages:
- build 
- test


#include: include template
#- template:  C++.gitlab-ci.yml

#image: gcc -- use docker image "gcc"

build:
  stage: build
  script:
    - cmake -B build -S .
    - cmake --build build --target Producer
  artifacts:
    paths:
      - build/Producer


# run tests using the binary built before
RunGTest:
   stage: test
   script:
    - cmake -B build -S .
    - cmake --build build --target GeneratorTest
    - build/GeneratorTest

# RunCTest:
#    stage: test
#    script:
#      - (cd build; ctest --output-on-failure -j6)